title: Andrew Duncan
description: Cell and Systems Biology PhD Candidate at the University of Toronto
logo: /assets/headshot.jpeg
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
